spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://authentication-service:8087
              predicates:
                - Path=/bank/api/v1/auth/client
              filters:
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 5
                  redis-rate-limiter.requestedTokens: 1
                  keyresolver: "#{@ipKeyResolver}"
            - id: client-person
              uri: http://client-person-service:8083
              predicates:
                - Path=/bank/api/v1/client/**
              filters:
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 5
                  redis-rate-limiter.burstCapacity: 10
                  redis-rate-limiter.requestedTokens: 1
                  keyresolver: "#{@tokenKeyResolver}"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak-service:8080/realms/bank-microservices-realm
  
  data:
    redis:
      host: redis-service
      port: 6379
      timeout: 2s

server:
  port: 8088
